export const MockUser = {
  id: 1,
  is_active: true,
  is_blocked: false,
  is_revendedor: true,
  team_leader_revendedor_id: 1,
  persona_non_grata: {
    reason: 'Usuário é golpista',
    created_at: '2020-05-23T08:00:00-02:00',
    restricao_ativa: true,
  },
  inactivation_reason: 'Vocês não atendem meu trecho Pirapozinha do Bom Jesus -> São José dos Pinhais',
  block_reason: 'Babaca que abusa do poder e dos bilhões de dólares que tem pra explorar os usuários de sua rede social',
  annotation: 'Assou umas carnes bem massas no quintal com os brothers',
  invitecode: 'cometanuncamais',
  first_name: 'Mark',
  name: 'Marco Antônio',
  fullname: 'Mark Elliot Zuckerberg',
  birth_date: '1984-05-14',
  email: 'zuck@facebook.com',
  photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Mark_Zuckerberg_em_setembro_de_2014.jpg/430px-Mark_Zuckerberg_em_setembro_de_2014.jpg',
  cell_phone: '12981804732',
  cell_phone_confirmed: false,
  first_travel: true,
  next_travel: {
    id: 1,
    reservation_code: 'ASIDHA',
    grupo: {
      id: 1,
      trecho_id: 2,
      rota: {
        id: 1,
        confirming_probability: 'very_low',
        status: 'pending',
        itinerario: [
          {
            local: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            id: 105,
            distancia_km: 0,
            arrival: null,
            departure: '2020-03-20T21:48:49.281Z',
          },
          {
            local: {
              id: 516,
              name: 'Campo Grande',
              uf: 'MS',
              slug: 'campo-grande-ms',
              sigla: 'CGR',
              timezone: 'America/Campo_Grande',
              nickname: 'Terminal Rodoviário Campo Grande',
              endereco: 'Avenida Gury Marques, 1215 - Residencial Betaville',
              ativo: true,
              cidade_id: 33,
              count_groups: 19454,
              nickname_slug: 'terminal-rodoviario-campo-grande',
              endereco_slug: 'avenida-gury-marques-1215-residencial-betaville',
              endereco_logradouro: 'Avenida Gury Marques',
              endereco_numero: '1215',
              endereco_bairro: 'Residencial Betaville',
              bairro_slug: 'residencial-betaville',
              endereco_cep: '79063000',
              endereco_referencia: null,
              description: '\n',
              classification: 'terminal_rodoviario',
              mapurl: 'https://bit.ly/3hN8TdS',
              coords: {
                latitude: -20.5135666,
                longitude: -54.6012315,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 0,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [],
            },
            id: 616,
            distancia_km: 180,
            arrival: '2020-03-20T21:48:49.281Z',
            departure: null,
          },
        ],
        trechos_vendidos: [
          {
            id: 1,
            checkpoint_origem_id: 105,
            checkpoint_destino_id: 616,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 516,
              name: 'Campo Grande',
              uf: 'MS',
              slug: 'campo-grande-ms',
              sigla: 'CGR',
              timezone: 'America/Campo_Grande',
              nickname: 'Terminal Rodoviário Campo Grande',
              endereco: 'Avenida Gury Marques, 1215 - Residencial Betaville',
              ativo: true,
              cidade_id: 33,
              count_groups: 19454,
              nickname_slug: 'terminal-rodoviario-campo-grande',
              endereco_slug: 'avenida-gury-marques-1215-residencial-betaville',
              endereco_logradouro: 'Avenida Gury Marques',
              endereco_numero: '1215',
              endereco_bairro: 'Residencial Betaville',
              bairro_slug: 'residencial-betaville',
              endereco_cep: '79063000',
              endereco_referencia: null,
              description: '\n',
              classification: 'terminal_rodoviario',
              mapurl: 'https://bit.ly/3hN8TdS',
              coords: {
                latitude: -20.5135666,
                longitude: -54.6012315,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 0,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [],
            },
            preco_rodoviaria: 150,
            rateio_sugerido_map: {
              executivo: 100,
              'semi leito': 120,
              leito: 150,
              'leito cama': 180,
            },
            pessoas: 0,
          },
          {
            id: 2,
            checkpoint_origem_id: 105,
            checkpoint_destino_id: 129,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 29,
              name: 'Rio de Janeiro',
              uf: 'RJ',
              slug: 'rio-de-janeiro-rj',
              sigla: 'RIO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Posto GNV Glória',
              endereco: 'Avenida Beira Mar, 3587 - Glória',
              ativo: true,
              cidade_id: 39,
              count_groups: 20867,
              nickname_slug: 'posto-gnv-gloria',
              endereco_slug: 'posto-gnv-gloria-av-beira-mar-3587-em-frente-ao-hotel-gloria',
              endereco_logradouro: 'Avenida Beira Mar',
              endereco_numero: '3587',
              endereco_bairro: 'Glória',
              bairro_slug: 'gloria',
              endereco_cep: '20021060',
              endereco_referencia: 'Estacionamento em frente as ruínas do antigo Hotel Glória, ao lado do Posto de Gasolina GNV Glória.',
              description: 'O local de embarque fica situado na Avenida Beira Mar 3587, no estacionamento ao lado do Posto de Gasolina GNV Glória. Em frente ao Hotel da glória.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -22.9217801,
                longitude: -43.1724609,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 5,
              requires_auth: true,
              onibus_suportados: [
                'toco',
                'ld',
                'trucado',
                'dd',
                'micro-onibus',
              ],
              platforms: [],
            },
            preco_rodoviaria: 130,
            rateio_sugerido_map: {
              executivo: 200,
              'semi leito': 220,
              leito: 250,
              'leito cama': 280,
            },
            pessoas: 4,
          },
          {
            id: 3,
            checkpoint_origem_id: 233,
            checkpoint_destino_id: 616,
            origem: {
              id: 133,
              name: 'Belo Horizonte',
              uf: 'MG',
              slug: 'belo-horizonte-mg',
              sigla: 'BHZ',
              timezone: 'America/Sao_Paulo',
              nickname: 'Edificio Savannah Mall',
              endereco: 'Rua Araguari, 359 - Barro Preto',
              ativo: true,
              cidade_id: 15,
              count_groups: 21079,
              nickname_slug: 'edificio-savannah-mall',
              endereco_slug: 'rua-araguari-359-barro-preto-edificio-savannah-mall',
              endereco_logradouro: 'Rua Araguari',
              endereco_numero: '359',
              endereco_bairro: 'Barro Preto',
              bairro_slug: 'barro-preto',
              endereco_cep: '30190110',
              endereco_referencia: ' Em frente ao Savannah Mall, ao lado do Shopping Barro Preto.',
              description: 'Embarque e desembarque serão realizados em frente ao Savannah Mall.',
              classification: 'ponto_de_rua',
              mapurl: 'http://bit.ly/2qKzAcX',
              coords: {
                latitude: -19.9210253,
                longitude: -43.9491071,
              },
              working_hour_list: [
                {
                  dia: 1,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 2,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 3,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 4,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 5,
                  start_time: '10:00',
                  end_time: '22:00',
                },
              ],
              max_embarque_simultaneo: null,
              requires_auth: false,
              onibus_suportados: [],
              platforms: [],
            },
            destino: {
              id: 516,
              name: 'Campo Grande',
              uf: 'MS',
              slug: 'campo-grande-ms',
              sigla: 'CGR',
              timezone: 'America/Campo_Grande',
              nickname: 'Terminal Rodoviário Campo Grande',
              endereco: 'Avenida Gury Marques, 1215 - Residencial Betaville',
              ativo: true,
              cidade_id: 33,
              count_groups: 19454,
              nickname_slug: 'terminal-rodoviario-campo-grande',
              endereco_slug: 'avenida-gury-marques-1215-residencial-betaville',
              endereco_logradouro: 'Avenida Gury Marques',
              endereco_numero: '1215',
              endereco_bairro: 'Residencial Betaville',
              bairro_slug: 'residencial-betaville',
              endereco_cep: '79063000',
              endereco_referencia: null,
              description: '\n',
              classification: 'terminal_rodoviario',
              mapurl: 'https://bit.ly/3hN8TdS',
              coords: {
                latitude: -20.5135666,
                longitude: -54.6012315,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 0,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [],
            },
            preco_rodoviaria: 135,
            rateio_sugerido_map: {
              executivo: 100,
              'semi leito': 120,
              leito: 150,
              'leito cama': 180,
            },
            pessoas: 1,
          },
        ],
        count_groups: 100,
        pax_count: 1251,
        duracao_total: 64000000,
        distancia_total: 660,
        ativo: true,
        sigla: 'SAO - CNS',
        ufs_intermediarios: '',
      },
      datetime_ida: '2020-03-20T19:48:49.281942-02:00',
      is_extra: false,
      status: 'travel_confirmed',
      tipo_assento: 'leito',
      notafiscal: {
        id: 112,
        numero: 1,
        serie: 2,
        status: 'paid',
        status_sefaz: 'autorizada',
        valor: 5.88,
        valor_pagamento: null,
        cnpj: '09.547.990/0001-57',
        data_competencia: null,
        data_emissao: '2019-12-12T11:11:00.224580-03:00',
        created_at: '2019-12-12T11:11:00.225666-03:00',
        discriminacao: null,
        payment: null,
        pago: false,
        data_vencimento: null,
        boleto_url: 'https://s3.bucket.notafiscal',
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        xml_url: 'https://www.w3schools.com/xml/note.xml',
        acao_sefaz: 'noop',
        provider: 'tecnospeed',
        status_parceiro: 'paga',
        emissao_auto: true,
      },
      confirming_probability: 'medium',
      travel_log: {
        created_at: '2018-12-17T17:59:57.200328+00:00',
        updated_at: '2018-12-17T18:00:11.504512+00:00',
        id: 4,
        status: 'in_route',
      },
      problem_description: 'Furou o pneu, o onibus capotou, ninguém se feriu, mas o ônibus está inutilizável, afinal de contas ele explodiu quando capotou, sad story mas é o que aconteceu, pois é né.',
      classes: [
        {
          id: 1,
          closed: false,
          closed_reason: null,
          closed_by: null,
          vagas: 12,
          pessoas: 8,
          max_capacity: 20,
          tipo_assento: 'leito',
        },
        {
          id: 2,
          closed: true,
          closed_reason: 'Savinho quer vaga',
          closed_by: 'Domingos Sávio',
          vagas: 11,
          pessoas: 18,
          max_capacity: 29,
          tipo_assento: 'leito cama',
        },
        {
          id: 3,
          closed: false,
          closed_reason: null,
          closed_by: null,
          vagas: 12,
          pessoas: 8,
          max_capacity: 20,
          tipo_assento: 'leito individual',
        },
      ],
      trechos_classes: {
        1: {
          1: {
            id: 1,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 133,
              name: 'Belo Horizonte',
              uf: 'MG',
              slug: 'belo-horizonte-mg',
              sigla: 'BHZ',
              timezone: 'America/Sao_Paulo',
              nickname: 'Edificio Savannah Mall',
              endereco: 'Rua Araguari, 359 - Barro Preto',
              ativo: true,
              cidade_id: 15,
              count_groups: 21079,
              nickname_slug: 'edificio-savannah-mall',
              endereco_slug: 'rua-araguari-359-barro-preto-edificio-savannah-mall',
              endereco_logradouro: 'Rua Araguari',
              endereco_numero: '359',
              endereco_bairro: 'Barro Preto',
              bairro_slug: 'barro-preto',
              endereco_cep: '30190110',
              endereco_referencia: ' Em frente ao Savannah Mall, ao lado do Shopping Barro Preto.',
              description: 'Embarque e desembarque serão realizados em frente ao Savannah Mall.',
              classification: 'ponto_de_rua',
              mapurl: 'http://bit.ly/2qKzAcX',
              coords: {
                latitude: -19.9210253,
                longitude: -43.9491071,
              },
              working_hour_list: [
                {
                  dia: 1,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 2,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 3,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 4,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 5,
                  start_time: '10:00',
                  end_time: '22:00',
                },
              ],
              max_embarque_simultaneo: null,
              requires_auth: false,
              onibus_suportados: [],
              platforms: [],
            },
            grupo_classe_id: 1,
            grupo_id: 1,
            trecho_vendido_id: 1,
            max_split_value: 23,
            split_value: 18,
            pessoas: 8,
            tipo_assento: 'executivo',
            preco_rodoviaria: 130,
            datetime_ida: '2021-09-26T06:30:00-03:00',
            status: 'APROVADO',
            pedido_alteracao_preco: [
              {
                id: 2,
                trecho_classe: 1,
                valor_novo: 120,
                valor_antigo: 100,
                created_by: 2,
                status: 'PENDENTE',
                created_at: '2021-09-26T06:30:00-03:00',
                updated_at: null,
                avaliado_by: null,
              },
              {
                id: 2,
                trecho_classe: 1,
                valor_novo: 120,
                valor_antigo: 100,
                created_by: 2,
                status: 'APROVADO',
                created_at: '2021-09-26T06:30:00-03:00',
                updated_at: null,
                avaliado_by: null,
              },
              {
                id: 1,
                trecho_classe: 1,
                valor_novo: 30,
                valor_antigo: 50,
                created_by: 2,
                status: 'APROVADO',
                created_at: '2020-09-26T06:30:00-03:00',
                updated_at: null,
                avaliado_by: null,
              },
            ],
          },
          2: {
            id: 2,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 133,
              name: 'Belo Horizonte',
              uf: 'MG',
              slug: 'belo-horizonte-mg',
              sigla: 'BHZ',
              timezone: 'America/Sao_Paulo',
              nickname: 'Edificio Savannah Mall',
              endereco: 'Rua Araguari, 359 - Barro Preto',
              ativo: true,
              cidade_id: 15,
              count_groups: 21079,
              nickname_slug: 'edificio-savannah-mall',
              endereco_slug: 'rua-araguari-359-barro-preto-edificio-savannah-mall',
              endereco_logradouro: 'Rua Araguari',
              endereco_numero: '359',
              endereco_bairro: 'Barro Preto',
              bairro_slug: 'barro-preto',
              endereco_cep: '30190110',
              endereco_referencia: ' Em frente ao Savannah Mall, ao lado do Shopping Barro Preto.',
              description: 'Embarque e desembarque serão realizados em frente ao Savannah Mall.',
              classification: 'ponto_de_rua',
              mapurl: 'http://bit.ly/2qKzAcX',
              coords: {
                latitude: -19.9210253,
                longitude: -43.9491071,
              },
              working_hour_list: [
                {
                  dia: 1,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 2,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 3,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 4,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 5,
                  start_time: '10:00',
                  end_time: '22:00',
                },
              ],
              max_embarque_simultaneo: null,
              requires_auth: false,
              onibus_suportados: [],
              platforms: [],
            },
            grupo_classe_id: 1,
            grupo_id: 1,
            trecho_vendido_id: 1,
            max_split_value: 34,
            split_value: 19,
            pessoas: 8,
            tipo_assento: 'leito',
            preco_rodoviaria: 130,
            datetime_ida: '2021-09-26T06:30:00-03:00',
            status: 'APROVADO',
            pedido_alteracao_preco: [],
          },
        },
        2: {
          1: {
            id: 3,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 133,
              name: 'Belo Horizonte',
              uf: 'MG',
              slug: 'belo-horizonte-mg',
              sigla: 'BHZ',
              timezone: 'America/Sao_Paulo',
              nickname: 'Edificio Savannah Mall',
              endereco: 'Rua Araguari, 359 - Barro Preto',
              ativo: true,
              cidade_id: 15,
              count_groups: 21079,
              nickname_slug: 'edificio-savannah-mall',
              endereco_slug: 'rua-araguari-359-barro-preto-edificio-savannah-mall',
              endereco_logradouro: 'Rua Araguari',
              endereco_numero: '359',
              endereco_bairro: 'Barro Preto',
              bairro_slug: 'barro-preto',
              endereco_cep: '30190110',
              endereco_referencia: ' Em frente ao Savannah Mall, ao lado do Shopping Barro Preto.',
              description: 'Embarque e desembarque serão realizados em frente ao Savannah Mall.',
              classification: 'ponto_de_rua',
              mapurl: 'http://bit.ly/2qKzAcX',
              coords: {
                latitude: -19.9210253,
                longitude: -43.9491071,
              },
              working_hour_list: [
                {
                  dia: 1,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 2,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 3,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 4,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 5,
                  start_time: '10:00',
                  end_time: '22:00',
                },
              ],
              max_embarque_simultaneo: null,
              requires_auth: false,
              onibus_suportados: [],
              platforms: [],
            },
            grupo_classe_id: 1,
            grupo_id: 1,
            trecho_vendido_id: 2,
            max_split_value: 56,
            split_value: 20,
            pessoas: 8,
            tipo_assento: 'executivo',
            preco_rodoviaria: 130,
            datetime_ida: '2021-09-26T06:30:00-03:00',
            status: 'APROVADO',
            pedido_alteracao_preco: [
              {
                id: 2,
                trecho_classe: 1,
                valor_novo: 120,
                valor_antigo: 100,
                created_by: 2,
                status: 'PENDENTE',
                created_at: '2021-09-26T06:30:00-03:00',
                updated_at: null,
                avaliado_by: null,
              },
              {
                id: 2,
                trecho_classe: 1,
                valor_novo: 120,
                valor_antigo: 100,
                created_by: 2,
                status: 'APROVADO',
                created_at: '2021-09-26T06:30:00-03:00',
                updated_at: null,
                avaliado_by: null,
              },
              {
                id: 1,
                trecho_classe: 1,
                valor_novo: 30,
                valor_antigo: 50,
                created_by: 2,
                status: 'APROVADO',
                created_at: '2020-09-26T06:30:00-03:00',
                updated_at: null,
                avaliado_by: null,
              },
            ],
          },
          2: {
            id: 4,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 133,
              name: 'Belo Horizonte',
              uf: 'MG',
              slug: 'belo-horizonte-mg',
              sigla: 'BHZ',
              timezone: 'America/Sao_Paulo',
              nickname: 'Edificio Savannah Mall',
              endereco: 'Rua Araguari, 359 - Barro Preto',
              ativo: true,
              cidade_id: 15,
              count_groups: 21079,
              nickname_slug: 'edificio-savannah-mall',
              endereco_slug: 'rua-araguari-359-barro-preto-edificio-savannah-mall',
              endereco_logradouro: 'Rua Araguari',
              endereco_numero: '359',
              endereco_bairro: 'Barro Preto',
              bairro_slug: 'barro-preto',
              endereco_cep: '30190110',
              endereco_referencia: ' Em frente ao Savannah Mall, ao lado do Shopping Barro Preto.',
              description: 'Embarque e desembarque serão realizados em frente ao Savannah Mall.',
              classification: 'ponto_de_rua',
              mapurl: 'http://bit.ly/2qKzAcX',
              coords: {
                latitude: -19.9210253,
                longitude: -43.9491071,
              },
              working_hour_list: [
                {
                  dia: 1,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 2,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 3,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 4,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 5,
                  start_time: '10:00',
                  end_time: '22:00',
                },
              ],
              max_embarque_simultaneo: null,
              requires_auth: false,
              onibus_suportados: [],
              platforms: [],
            },
            grupo_classe_id: 2,
            grupo_id: 1,
            trecho_vendido_id: 2,
            max_split_value: 67,
            split_value: 21,
            pessoas: 8,
            tipo_assento: 'leito',
            preco_rodoviaria: 130,
            datetime_ida: '2021-09-26T06:30:00-03:00',
            status: 'APROVADO',
            pedido_alteracao_preco: [],
          },
        },
        3: {
          1: {
            id: 5,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 133,
              name: 'Belo Horizonte',
              uf: 'MG',
              slug: 'belo-horizonte-mg',
              sigla: 'BHZ',
              timezone: 'America/Sao_Paulo',
              nickname: 'Edificio Savannah Mall',
              endereco: 'Rua Araguari, 359 - Barro Preto',
              ativo: true,
              cidade_id: 15,
              count_groups: 21079,
              nickname_slug: 'edificio-savannah-mall',
              endereco_slug: 'rua-araguari-359-barro-preto-edificio-savannah-mall',
              endereco_logradouro: 'Rua Araguari',
              endereco_numero: '359',
              endereco_bairro: 'Barro Preto',
              bairro_slug: 'barro-preto',
              endereco_cep: '30190110',
              endereco_referencia: ' Em frente ao Savannah Mall, ao lado do Shopping Barro Preto.',
              description: 'Embarque e desembarque serão realizados em frente ao Savannah Mall.',
              classification: 'ponto_de_rua',
              mapurl: 'http://bit.ly/2qKzAcX',
              coords: {
                latitude: -19.9210253,
                longitude: -43.9491071,
              },
              working_hour_list: [
                {
                  dia: 1,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 2,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 3,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 4,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 5,
                  start_time: '10:00',
                  end_time: '22:00',
                },
              ],
              max_embarque_simultaneo: null,
              requires_auth: false,
              onibus_suportados: [],
              platforms: [],
            },
            grupo_classe_id: 1,
            trecho_vendido_id: 3,
            grupo_id: 1,
            max_split_value: 89,
            split_value: 22,
            pessoas: 8,
            tipo_assento: 'executivo',
            preco_rodoviaria: 130,
            datetime_ida: '2021-09-26T06:30:00-03:00',
            status: 'APROVADO',
            pedido_alteracao_preco: [],
          },
          2: {
            id: 6,
            origem: {
              id: 5,
              name: 'São Paulo',
              uf: 'SP',
              slug: 'sao-paulo-sp',
              sigla: 'SAO',
              timezone: 'America/Sao_Paulo',
              nickname: 'Estacionamento Tietê',
              endereco: 'Rua Voluntários da Pátria, 344 - Santana',
              ativo: true,
              cidade_id: 16,
              count_groups: 69751,
              nickname_slug: 'estacione-tiete',
              endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
              endereco_logradouro: 'Rua Voluntários da Pátria',
              endereco_numero: '344',
              endereco_bairro: 'Santana',
              bairro_slug: 'santana',
              endereco_cep: '02010000',
              endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
              description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
              classification: 'estacionamento',
              mapurl: 'http://bit.ly/blah',
              coords: {
                latitude: -23.517392,
                longitude: -46.6288297,
              },
              working_hour_list: [],
              max_embarque_simultaneo: 15,
              requires_auth: true,
              onibus_suportados: [
                'micro-onibus',
                'dd',
                'ld',
                'trucado',
                'toco',
              ],
              platforms: [
                {
                  id: 1,
                  numero: 1,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
                {
                  id: 2,
                  numero: 2,
                  desembarque: false,
                  local_id: 1,
                  destinos: [
                    {
                      id: 94,
                      name: 'Natal',
                      uf: 'RN',
                      slug: 'natal-rn',
                      sigla: 'NTL',
                      timezone: 'America/Fortaleza',
                    },
                    {
                      id: 16,
                      name: 'São Paulo',
                      uf: 'SP',
                      slug: 'sao-paulo-sp',
                      sigla: 'SAO',
                      timezone: 'America/Sao_Paulo',
                    },
                  ],
                },
              ],
            },
            destino: {
              id: 133,
              name: 'Belo Horizonte',
              uf: 'MG',
              slug: 'belo-horizonte-mg',
              sigla: 'BHZ',
              timezone: 'America/Sao_Paulo',
              nickname: 'Edificio Savannah Mall',
              endereco: 'Rua Araguari, 359 - Barro Preto',
              ativo: true,
              cidade_id: 15,
              count_groups: 21079,
              nickname_slug: 'edificio-savannah-mall',
              endereco_slug: 'rua-araguari-359-barro-preto-edificio-savannah-mall',
              endereco_logradouro: 'Rua Araguari',
              endereco_numero: '359',
              endereco_bairro: 'Barro Preto',
              bairro_slug: 'barro-preto',
              endereco_cep: '30190110',
              endereco_referencia: ' Em frente ao Savannah Mall, ao lado do Shopping Barro Preto.',
              description: 'Embarque e desembarque serão realizados em frente ao Savannah Mall.',
              classification: 'ponto_de_rua',
              mapurl: 'http://bit.ly/2qKzAcX',
              coords: {
                latitude: -19.9210253,
                longitude: -43.9491071,
              },
              working_hour_list: [
                {
                  dia: 1,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 2,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 3,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 4,
                  start_time: '10:00',
                  end_time: '22:00',
                },
                {
                  dia: 5,
                  start_time: '10:00',
                  end_time: '22:00',
                },
              ],
              max_embarque_simultaneo: null,
              requires_auth: false,
              onibus_suportados: [],
              platforms: [],
            },
            grupo_classe_id: 2,
            grupo_id: 1,
            trecho_vendido_id: 3,
            max_split_value: 90,
            split_value: 23,
            pessoas: 8,
            tipo_assento: 'leito',
            preco_rodoviaria: 130,
            datetime_ida: '2021-09-26T06:30:00-03:00',
            status: 'APROVADO',
            pedido_alteracao_preco: [],
          },
        },
      },
      checkpoint_idx: 1,
      checkin_status: 'travel_done',
      checkpoints_datetime: '{"0":{"checkin_open":"2022-02-01T19:35:32.947-03:00","checkin_closed":"2022-02-01T20:05:32.947-03:00"},"1":{"checkin_open":"2022-02-01T21:35:32.947-03:00"}}',
      company_name: 'blah',
      empresa_name: 'blah',
      empresa: {
        name: 'blah',
      },
      empresa_id: 1,
      driver_one: 'Cristiano Ronaldo da Silva',
      company_operational_phone: '12988888888',
      is_marketplace: false,
      onibus: {
        id: 1,
        name: 'Verde Seriema Topzera',
        alias: 'DBZ6060 (Empresa)',
        placa: 'DBZ6060',
        renavam: '0123456789',
        uf: 'SP',
        ano: '2017',
        ano_modelo: '2017',
        ano_fabricacao: '2018',
        count_groups: 15,
        next_group: null,
        last_group: null,
        classes: [
          {
            tipo: 'leito',
            capacidade: 10,
            capacidade_vendida: 10,
          },
          {
            tipo: 'semi leito',
            capacidade: 10,
            capacidade_vendida: 10,
          },
          {
            tipo: 'leito cama',
            capacidade: 10,
            capacidade_vendida: 10,
          },
        ],
        removed: false,
        marca: 'Chassi',
        modelo: 'Carroceria',
        motor: 'motor',
        tipo: 'toco',
        data_vencimento_dut: '2019-01-01T08:00:00-02:00',
        data_vencimento_seguro: '2019-01-01T08:00:00-02:00',
        foto_dut: 'https://www.checkauto.com.br/Blog/Imagem?ImagemId=50',
        foto_placa: 'https://extra.globo.com/incoming/13331306-425-d4e/w448/2014-735485115-img-20140721-wa0051_20140721.jpg?AWSAccessKeyId=kkk&Signature=xxxx&Expires=123123',
        foto_interna: 'https://mobilidadesampa.com.br/wp-content/uploads/2020/08/Onibus-wemobi.jpeg',
        foto_seguro: 'https://blah-prod.s3.amazonaws.com/onibus/2020-03-10-LCUE/foto_seguro-19.pdf?AWSAccessKeyId=AKIAIKTD26PJNUEBV4XQ&Signature=tcKagGUC0CE%2Fzx%2FM6vWRu7PdzMM%3D&Expires=1584534556',
        possui_plotagem_blah: true,
        possui_seguro_blah: true,
        pendente_em: '2018-07-03T18:23:00-02:00',
        jsondata: {
          features: [
            'telemetria',
            'camera_fadiga',
            'plotagem_blah',
          ],
          licences: [
            'DER_PB',
          ],
        },
        infos: {
          dut: {
            numeracao: '1234562',
            foto: 'https://tirarhabilitacao.com/wp-content/uploads/2018/03/perdi-o-dut.jpg',
            status: 'pendente',
            mensagem: 'vai dar certo, só não sei como',
            data_vencimento: '2019-01-01T08:00:00-02:00',
            thumbnail: null,
            updated_at: '2020-07-03T18:23:00-02:00',
          },
          foto_externa: {
            numeracao: null,
            foto: 'https://ogimg.infoglobo.com.br/rio/23940882-193-3b8/FT1086A/652/onibus-blah.jpg',
            status: 'aprovado',
            mensagem: 'vai dar certo, só não sei como',
            data_vencimento: null,
            thumbnail: 'https://mobilidadesampa.com.br/wp-content/uploads/2020/08/Onibus-wemobi.jpeg',
            updated_at: '2020-07-03T18:23:00-02:00',
          },
          seguro: {
            numeracao: 'sdujhfailswhubdfiauh2222bjka',
            foto: 'https://www.humberseguros.com.br/cotacaoEstagiario/imagens/apolice-ex.jpg',
            status: 'aprovado',
            mensagem: 'vai dar certo, só não sei como',
            data_vencimento: '2019-01-01T08:00:00-02:00',
            thumbnail: null,
            updated_at: '2020-07-03T18:23:00-02:00',
          },
          assentos: {
            numeracao: '',
            foto: '',
            status: 'aprovado',
            mensagem: '',
            data_vencimento: '',
            thumbnail: null,
            updated_at: '2020-07-03T18:23:00-02:00',
          },
        },
        company: {
          id: 1,
          kind: 'COMPANY',
          bank_account: {
            agencia: '1234',
            agencia_dv: '1',
            bank_code: '237',
            conta: '123412',
            conta_dv: '2',
            document_number: '414.040.298-93',
            legal_name: 'Sireima Fretes',
          },
          name: 'Sireima',
          payment_option: 'Depósito',
        },
      },
      onibus_placa: 'DBZ6666',
      motorista_descansado: {},
      modelo_venda: 'blah',
      events: [
        {
          id: 12078,
          ativo: true,
          parada: {
            id: 5,
            name: 'São Paulo',
            uf: 'SP',
            slug: 'sao-paulo-sp',
            sigla: 'SAO',
            timezone: 'America/Sao_Paulo',
            nickname: 'Estacionamento Tietê',
            endereco: 'Rua Voluntários da Pátria, 344 - Santana',
            ativo: true,
            cidade_id: 16,
            count_groups: 69751,
            nickname_slug: 'estacione-tiete',
            endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
            endereco_logradouro: 'Rua Voluntários da Pátria',
            endereco_numero: '344',
            endereco_bairro: 'Santana',
            bairro_slug: 'santana',
            endereco_cep: '02010000',
            endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
            description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
            classification: 'estacionamento',
            mapurl: 'http://bit.ly/blah',
            coords: {
              latitude: -23.517392,
              longitude: -46.6288297,
            },
            working_hour_list: [],
            max_embarque_simultaneo: 15,
            requires_auth: true,
            onibus_suportados: [
              'micro-onibus',
              'dd',
              'ld',
              'trucado',
              'toco',
            ],
            platforms: [
              {
                id: 1,
                numero: 1,
                desembarque: false,
                local_id: 1,
                destinos: [
                  {
                    id: 94,
                    name: 'Natal',
                    uf: 'RN',
                    slug: 'natal-rn',
                    sigla: 'NTL',
                    timezone: 'America/Fortaleza',
                  },
                  {
                    id: 16,
                    name: 'São Paulo',
                    uf: 'SP',
                    slug: 'sao-paulo-sp',
                    sigla: 'SAO',
                    timezone: 'America/Sao_Paulo',
                  },
                ],
              },
              {
                id: 2,
                numero: 2,
                desembarque: false,
                local_id: 1,
                destinos: [
                  {
                    id: 94,
                    name: 'Natal',
                    uf: 'RN',
                    slug: 'natal-rn',
                    sigla: 'NTL',
                    timezone: 'America/Fortaleza',
                  },
                  {
                    id: 16,
                    name: 'São Paulo',
                    uf: 'SP',
                    slug: 'sao-paulo-sp',
                    sigla: 'SAO',
                    timezone: 'America/Sao_Paulo',
                  },
                ],
              },
            ],
          },
          coordinates: {
            latitude: -19.92374,
            longitude: -43.94559,
          },
          alert_datetime: '2020-02-17T13:45:15.981082+00:00',
          is_fined: true,
          traces_id: 9629559947,
        },
        {
          id: 12665,
          ativo: true,
          parada: {
            id: 5,
            name: 'São Paulo',
            uf: 'SP',
            slug: 'sao-paulo-sp',
            sigla: 'SAO',
            timezone: 'America/Sao_Paulo',
            nickname: 'Estacionamento Tietê',
            endereco: 'Rua Voluntários da Pátria, 344 - Santana',
            ativo: true,
            cidade_id: 16,
            count_groups: 69751,
            nickname_slug: 'estacione-tiete',
            endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
            endereco_logradouro: 'Rua Voluntários da Pátria',
            endereco_numero: '344',
            endereco_bairro: 'Santana',
            bairro_slug: 'santana',
            endereco_cep: '02010000',
            endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
            description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
            classification: 'estacionamento',
            mapurl: 'http://bit.ly/blah',
            coords: {
              latitude: -23.517392,
              longitude: -46.6288297,
            },
            working_hour_list: [],
            max_embarque_simultaneo: 15,
            requires_auth: true,
            onibus_suportados: [
              'micro-onibus',
              'dd',
              'ld',
              'trucado',
              'toco',
            ],
            platforms: [
              {
                id: 1,
                numero: 1,
                desembarque: false,
                local_id: 1,
                destinos: [
                  {
                    id: 94,
                    name: 'Natal',
                    uf: 'RN',
                    slug: 'natal-rn',
                    sigla: 'NTL',
                    timezone: 'America/Fortaleza',
                  },
                  {
                    id: 16,
                    name: 'São Paulo',
                    uf: 'SP',
                    slug: 'sao-paulo-sp',
                    sigla: 'SAO',
                    timezone: 'America/Sao_Paulo',
                  },
                ],
              },
              {
                id: 2,
                numero: 2,
                desembarque: false,
                local_id: 1,
                destinos: [
                  {
                    id: 94,
                    name: 'Natal',
                    uf: 'RN',
                    slug: 'natal-rn',
                    sigla: 'NTL',
                    timezone: 'America/Fortaleza',
                  },
                  {
                    id: 16,
                    name: 'São Paulo',
                    uf: 'SP',
                    slug: 'sao-paulo-sp',
                    sigla: 'SAO',
                    timezone: 'America/Sao_Paulo',
                  },
                ],
              },
            ],
          },
          coordinates: {
            latitude: -19.92374,
            longitude: -43.94559,
          },
          alert_datetime: '2020-02-17T14:05:07.553700+00:00',
          is_fined: false,
          traces_id: 9629577759,
        },
        {
          id: 12077,
          ativo: true,
          parada: {
            id: 5,
            name: 'São Paulo',
            uf: 'SP',
            slug: 'sao-paulo-sp',
            sigla: 'SAO',
            timezone: 'America/Sao_Paulo',
            nickname: 'Estacionamento Tietê',
            endereco: 'Rua Voluntários da Pátria, 344 - Santana',
            ativo: true,
            cidade_id: 16,
            count_groups: 69751,
            nickname_slug: 'estacione-tiete',
            endereco_slug: 'rua-voluntarios-da-patria-344-dentro-do-estacionamento',
            endereco_logradouro: 'Rua Voluntários da Pátria',
            endereco_numero: '344',
            endereco_bairro: 'Santana',
            bairro_slug: 'santana',
            endereco_cep: '02010000',
            endereco_referencia: 'Estacionamento ao lado do Terminal Rodoviário Tietê e próximo da Estação Portuguesa Tietê de Metrô.',
            description: 'O local de embarque fica dentro do estacionamento particular ao lado da rodoviária Tietê. Caso venha de carro, entre pela Rua Voluntários da Pátria 344. Caso venha de metrô, pare na estação Tietê, procure a saída D - SANTANA, TUCURUVI, e saia na Rua Marechal Odylio Denys, ande 30 metros para a esquerda e entre na entrada do estacionamento, número 138.\r\nO embarque fica próximo as 2 chaminés localizadas dentro do estacionamento.',
            classification: 'estacionamento',
            mapurl: 'http://bit.ly/blah',
            coords: {
              latitude: -23.517392,
              longitude: -46.6288297,
            },
            working_hour_list: [],
            max_embarque_simultaneo: 15,
            requires_auth: true,
            onibus_suportados: [
              'micro-onibus',
              'dd',
              'ld',
              'trucado',
              'toco',
            ],
            platforms: [
              {
                id: 1,
                numero: 1,
                desembarque: false,
                local_id: 1,
                destinos: [
                  {
                    id: 94,
                    name: 'Natal',
                    uf: 'RN',
                    slug: 'natal-rn',
                    sigla: 'NTL',
                    timezone: 'America/Fortaleza',
                  },
                  {
                    id: 16,
                    name: 'São Paulo',
                    uf: 'SP',
                    slug: 'sao-paulo-sp',
                    sigla: 'SAO',
                    timezone: 'America/Sao_Paulo',
                  },
                ],
              },
              {
                id: 2,
                numero: 2,
                desembarque: false,
                local_id: 1,
                destinos: [
                  {
                    id: 94,
                    name: 'Natal',
                    uf: 'RN',
                    slug: 'natal-rn',
                    sigla: 'NTL',
                    timezone: 'America/Fortaleza',
                  },
                  {
                    id: 16,
                    name: 'São Paulo',
                    uf: 'SP',
                    slug: 'sao-paulo-sp',
                    sigla: 'SAO',
                    timezone: 'America/Sao_Paulo',
                  },
                ],
              },
            ],
          },
          coordinates: {
            latitude: -19.93483,
            longitude: -44.17489,
          },
          alert_datetime: '2020-02-17T12:50:16.766622+00:00',
          is_fined: null,
          traces_id: 9629596695,
        },
      ],
      feedbacks: [
        {
          nota: 1,
          id: 2,
          tags: [
            'Desembarque',
            'Direção',
          ],
          comentario: '',
          user: {
            name: 'Marina Silva',
            photo_url: 'https://randomuser.me/api/portraits/thumb/women/20.jpg',
          },
        },
        {
          nota: 4.5,
          id: 3,
          tags: [],
          comentario: 'O motorista foi muito atencioso e facilitou muito a minha vida ao fazer uma parada e me deixar descer na praça da Cemig. Muito Obrigada',
          user: {
            name: 'Luís Inácio',
            photo_url: 'https://randomuser.me/api/portraits/thumb/men/24.jpg',
          },
        },
      ],
      nota: 2.5121570702930693,
      driver_two: 'Lewandowski do Corsa',
      closed: false,
      closed_reason: null,
      closed_by: null,
      vagas: 12,
      pessoas: 8,
      max_capacity: 20,
    },
    status: 'travel_confirmed',
    canceled_reason: null,
    email: 'fabio@aoisdjoais.omo',
    phone: '(12) 98144-0013',
  },
  first_payment: true,
  complete_registration: false,
  verification_status: 'verified',
  verification_rejection_reason: 'Foto bonita demais pra alguém tão feio',
  cpf: '12345678911',
  rg: '123456789',
  passaporte: '12345678910',
  saldo: {
    buedas: 32.93,
    reais: -40,
    sacavel: 39,
    estornavel: 40,
  },
  company: {
    antt_enabled: true,
    id: 142,
    name: 'Seriema',
    cnpj: '30.049.413/0001-21',
    inscricao_estadual: '123456789',
    razao_social: 'Seriema Fretamentos S.A.',
    nome_fantasia: 'Seriema Fretamento',
    endereco_logradouro: 'Rua dos Fretadores',
    endereco_numero: '569',
    endereco_bairro: 'Centro',
    endereco_cep: '12222896',
    phone: '11999999999',
    taf: '000000012546',
    cidade: {
      id: 1,
      cidade_id: 1,
      name: 'Belo Horizonte',
      uf: 'MG',
      slug: 'belo-horizonte-mg',
      sigla: 'BHZ',
    },
    aliquota_federal: 13.5,
    has_accepted_contract: true,
    emissao_nf_enabled: true,
    is_simples_nacional: false,
    cteos_serie: 2,
    datetime_expiracao_certificado: '2020-05-23T08:00:00-02:00',
    saque_enabled: true,
    vinculos_reais: [
      'fretamento',
      'marketplace',
    ],
  },
  permissions: {
    STAFF: true,
    REVENDEDOR: true,
    CAN_PAY_WITH_MONEY: false,
    SUPORTE: true,
    SUPORTE_LIDER: true,
    OPS: true,
    ROTAS: true,
    INFRA: true,
    BO: true,
    COMERCIAL: true,
    QUALIDADE: true,
    MARKETING: true,
    FINANCIAL: true,
    PODE_GERENCIAR_EMPRESTIMO: true,
    CAN_GIVE_REAIS: true,
    CAN_RESERVAR_POLTRONA: true,
    COMPANY: true,
    CARTEIRA_PARCEIRO: true,
    ESCRITOR: true,
    PAGAR_BO: true,
    SEGURANCA: true,
    CAN_LEND_TO_COMPANY: true,
    ENVIAR_AVISOS_MOTORISTA: true,
    GROWTH: true,
  },
  bank_account: {
    agencia: '1111',
    agencia_dv: '1',
    bank_code: '001',
    conta: '11111111',
    conta_dv: '1',
    document_number: '11111111111',
    legal_name: 'Jose da Silva',
  },
  cached_passengers: [
    {
      id: 1,
      name: 'Mark Zuckerberg',
      email: 'zuck@facebook.com',
      cpf: '59770745065',
      rg_number: '235567810',
      rg_orgao: 'SP',
      birthday: '10061981',
      phone: '12981440013',
    },
    {
      id: 2,
      name: 'Steve Jobs',
      rg_number: '10987654321',
      rg_orgao: 'SSP-SP',
      birthday: '04021982',
      cpf: '68092760098',
    },
  ],
};
